version: '3'
services:
  redis:
    image: redis:5.0-alpine3.15
    entrypoint:
     - redis-server
     - /usr/local/etc/redis/redis.conf
    environment:
     - REDISCLI_AUTH=password
    volumes:
     - ./Configs/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
     - "6379:6379"
  postgres:
    image: postgres:11-alpine3.15
    environment:
      POSTGRES_PASSWORD: password
    volumes:
    - ./Configs/postgresql.conf:/var/lib/postgresql/postgresql.conf
    - ./Configs/pg_hba.conf:/var/lib/postgresql/pg_hba.conf
    ports:
      - "5432:5432"